#!/bin/sh
# The ppp ip-up script for StrongSwan L2TP ppp link-up

# When the ppp link comes up, this script is called with the following
# parameters
#       $1      the interface name used by pppd (e.g. ppp3)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd

if [ "$4" == "10.1.20.1" ]; then
	killall -SIGHUP minidlna
fi

exit 0
