#!/bin/sh
scene_id=$1
action=`sqlite3 /etc/orbweb.db "select action from ifttt where HA_NO=$scene_id"`
action_json=`echo $action | sed s/\"/\'/g`
echo $action_json
MAC=`ifconfig eth0 | grep HWaddr | awk '{print $5}'`
curl -X POST -H 'Content-Type: application/x-www-form-urlencoded'\
 --data-urlencode 'strXML=<?xml version="1.0" encoding="UTF-8"?><p><mac v="'$MAC'"/><cmds><referer v="panel/cgi"/><cmd a="triggerScene" id="12345678"><scene v="'$scene_id'"/><action v="'"$action_json"'" /><ret>1</ret><m>OK</m></cmd></cmds></p>' app1.gizmosmart.io:8902/iot/tst_srvr/1.3/public/poll
