#!/bin/sh /etc/rc.common
# Copyright (C) 2010 Jo-Philipp Wich

START=50

USE_PROCD=1

MONGOOSE_BIN="/sbin/mongoose"

append_arg() {
	local cfg="$1"
	local var="$2"
	local opt="$3"
	local def="$4"
	local val

	config_get val "$cfg" "$var"
	[ -n "$val" -o -n "$def" ] && procd_append_param command "$opt" "${val:-$def}"
}

start_instance()
{
	local cfg="$1"

	# set language file
	local lang=`uci get system.@system[0].langurage`
	ln -sf /etc/html/lang/"$lang".json /etc/html/lang/multilanguage.js
	ln -sf /etc/html/lang/"$lang".css /etc/html/default.css

	procd_open_instance

	procd_set_param respawn
	procd_set_param stderr 1
	procd_set_param command "$MONGOOSE_BIN"

	append_arg "$cfg" listening_ports "-p"
	append_arg "$cfg" authentication_domain "-R"
	append_arg "$cfg" global_auth_file "-g"
	append_arg "$cfg" document_root "-r"
	append_arg "$cfg" index_files "-i"
	append_arg "$cfg" thread_num "-t" "3"

	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "mongoose"
}

start_service() {
	config_load mongoose
	config_foreach start_instance mongoose
}
