#!/bin/sh /etc/rc.common
# Copyright (C) 2010 Jo-Philipp Wich

START=50
USE_PROCD=1
ZSTACK_BIN="/zias/zigbeeHAgw"

upgrade_znp ()
{
	zb_sbl $1 0 1
	rm -f /tmp/sysinfo/znp_version

	i=0
	while [ "$i" != "3" ]
	do
		/zias/zigbee_reset.sh
		/zias/read_znp_version
		if [ -e /tmp/sysinfo/znp_version ]; then
			break
		fi
		i=$(($i+1))
	done
}

start_service()
{
	is_znp_ready=0

	echo "[$(date)] ########### zigbee ############" > /dev/console
	logger -t warning zigbee start
	if [ -f /usr/sbin/x10-diag ]; then
		exit 1
	fi

	/zias/zigbee_reset.sh
	sleep 3

	i=0
	while [ "$i" != "3" ]
	do
		/zias/read_znp_version
		if [ -e /tmp/sysinfo/znp_version ]; then
			is_znp_ready=1
			break
		fi
		/zias/zigbee_reset.sh
		i=$(($i+1))
	done

	# if ZNP can't response the version, it would be the ZNP FW broken. 
	# Redonwlod ZNP FW to fix it.
	if [ $is_znp_ready == 0 ]; then
		IMG_FILE=`ls /zias/znp_*`
		upgrade_znp $IMG_FILE
	fi

	i=0
	while [ "$i" != "3" ]
	do
		/zias/read_zigbee_mac
		[ -e /tmp/sysinfo/zigbee_mac ] && break
		/zias/zigbee_reset.sh
		i=$(($i+1))
	done

	if [ -e /tmp/sysinfo/znp_version ] && [ -e /zias/znp*bin ]; then
		ZNP_VER1=`cat /tmp/sysinfo/znp_version | awk -F '.' '{print $1}'`
		ZNP_VER2=`cat /tmp/sysinfo/znp_version | awk -F '.' '{print $2}'`
		ZNP_VER3=`cat /tmp/sysinfo/znp_version | awk -F '.' '{print $3}'`
		IMG_FILE=`ls /zias/znp_*`
		IMG_VER1=`echo $IMG_FILE | awk -F '_' '{print $2}'`
		IMG_VER2=`echo $IMG_FILE | awk -F '_' '{print $3}'`
		IMG_VER3=`echo $IMG_FILE | awk -F '_' '{print $4}' | awk -F '.' '{print $1}'`

		if [ $IMG_VER1 -ne $ZNP_VER1 ] || [ $IMG_VER2 -ne $ZNP_VER2 ] || [ $IMG_VER3 -ne $ZNP_VER3 ]; then
			upgrade_znp $IMG_FILE
		fi	
	fi

	# kill all zstack processes
	[ ! -z $(pidof NPI_lnx_arm_server)] && kill -9 $(pidof NPI_lnx_arm_server)
	[ ! -z $(pidof ZLSZNP_arm)] && kill -9 $(pidof ZLSZNP_arm)
	[ ! -z $(pidof NWKMGR_SRVR_arm)] && kill -9 $(pidof NWKMGR_SRVR_arm)
	[ ! -z $(pidof GATEWAY_SRVR_arm)] && kill -9 $(pidof GATEWAY_SRVR_arm)

	procd_open_instance

	procd_set_param respawn ${respawn_threshold:-60} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param command "$ZSTACK_BIN"
	procd_close_instance
}

